### ISSUE TITLE
map and filter are obsolete, use list comprehensions

### ISSUE THREAD

**Issue by alberth** [yasoob/intermediatePython#131]
map replacement:

``` python
items = [1, 2, 3, 4, 5]
squared = [x*x for x in items]
```

this is simpler/less convoluted

(and `x*x` is waaay faster than `x**2`)

filter replacement:

``` python
number_list = range(-5, 5)
less_than_zero = [x for x in number_list if x < 0]
```

**Comment by MrMattBusby** [comment]
No...neither map nor filter are obsolete and are in both manuals. https://docs.python.org/3/library/functions.html

Since you didn't explain, I assume you're either referring to the comment in https://www.python.org/dev/peps/pep-0279/ , which was just a comment; or the Google Python Style Guide https://google.github.io/styleguide/pyguide.html , which would've been taken out of context if so. It mentions list comprehension is okay only for simple cases, which this is, but: Given this is an intermediate class introducing supposedly new constructs to learners I would recommend keeping both map and filter.

**Comment by alberth** [comment]
Our BDFL isn't much fan of the map, filter, and friends: http://www.artima.com/weblogs/viewpost.jsp?thread=98196

In my view, the biggest problems with map and filter here is that they force you to
1. understand functions as data objects (ie "f" rather than "f()"), which is a big step if you see that for the first time.
2. You combine that with implicit processing (unlike list comprehension, both filter and map do not explicitly show what they do), and
3. use in-line iteration over the list (without explicit "for statement" that says "we're looping over the list!")

That's 3 new concepts in one name "filter" or "map". This makes them more advanced than intermediate, imho. Yes they are great in functional programming, but in a language that aims to be explicit and readable for all, map and filter are better not mentioned until readers are fully understanding how list comprehension works (since at that point, it's merely a convenient abbreviation rather than 3 pieces of magic at the same time).

**Comment by yasoob** [comment]
There is a separate chapter on list and dict comprehensions as well so I don't see any major reason for removing this chapter. 

But still thank you very much for bringing this to my attention. :)
